version: "3.1"

services:
  db:
    build:
      context: ./
      dockerfile: db.dockerfile
    ports:
      - 5432:5432

  db-wait:
    image: jwilder/dockerize
    command: dockerize -wait tcp://db:5432 -timeout 1m
    depends_on:
      - db

  graphql:
    image: node:16.15.1
    command: ./node_modules/.bin/tsx watch -- src/server.ts
    working_dir: /home/node/app
    depends_on:
      - db
    env_file:
      - env/local.env
    environment:
      - DATABASE_URL=postgres://sample_user:local@localhost:5432/sample_app
    volumes:
      - ./:/home/node/app/
    ports:
      - 4000:4000
      - 9229:9229
